CSRF_ENABLED = False
SECRET_KEY = 'you-will-never-guess'
BOOTSTRAP_SERVE_LOCAL = True
SQLALCHEMY_DATABASE_URI = 'sqlite:///../database/wanglu.db'
SQLALCHEMY_ECHO = True
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_COMMIT_ON_TEARDOWN = True
